# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('aet', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SessionRest',
            fields=[
                ('sessionid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaticParameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proxyrest.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
