# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxyrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
